version: '3'
services:
  flask-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  go-app:
    build:
      context: ./modulo_Go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  csharp-module:
    build:
      context: ./modulo_C#
      dockerfile: dockerfile