version: '3'
services:
  flask-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  go-app:
    build:
      context: ./modulo_Go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"