version: '3'
services:
  flask-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python
    ports:
      - "8082:8082"

  go-app:
    build:
      context: ./modulo_Go
      dockerfile: Dockerfile
    container_name: go
    ports:
      - "8080:8080"


  # csharp-module:
  #   build:
  #     context: ./modulo_C#
  #     dockerfile: dockerfile